on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Create env file
        run: |
          touch .env
          echo DISCORD_=${{ secrets.DISCORD_BOT_TOKEN }} >> .env
          echo DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} >> .env
          echo UNI_USERNAME=${{ secrets.UNI_USERNAME }} >> .env
          echo UNI_PASSWORD=${{ secrets.UNI_PASSWORD }} >> .env

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: env $(cat .env | grep -v \"#\" | xargs) pm2 deploy ecosystem.config.js staging
        env:
          DEPLOY_PM2_HOST: ${{secrets.DEPLOY_PM2_HOST}}
          DEPLOY_PM2_USER: ${{secrets.DEPLOY_PM2_USER}}